// <auto-generated />
using System;
using Buyit.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Buyit.Migrations
{
    [DbContext(typeof(BuyitContext))]
    [Migration("20240328175458_FirstOracleDatabase")]
    partial class FirstOracleDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Buyit.Models.AvaliacaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CotacaoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NotaEntrega")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NotaPreco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NotaQualidade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("Buyit.Models.ContatoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("UsuarioId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Buyit.Models.CotacaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CompradorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Prazo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PrioridadeEntrega")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PrioridadePreco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PrioridadeQualidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("QuantidadeProduto")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<long>("StatusId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("ValorProduto")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("StatusId");

                    b.ToTable("Cotacao");
                });

            modelBuilder.Entity("Buyit.Models.DepartamentoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Icone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Buyit.Models.HistoricoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CotacaoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("RecusadoPorPrazo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("RecusadoPorPreco")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("RecusadoPorProduto")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("RecusadoPorQuantidade")
                        .HasColumnType("NUMBER(1)");

                    b.Property<long>("StatusId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal?>("ValorOfertado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("StatusId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("Buyit.Models.ProdutoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cor")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("DepartamentoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Marca")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Material")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tamanho")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Buyit.Models.StatusModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Buyit.Models.TagModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Buyit.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsFornecedor")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DepartamentoModelTagModel", b =>
                {
                    b.Property<long>("DepartamentosId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TagsId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("DepartamentosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DepartamentoModelTagModel");
                });

            modelBuilder.Entity("ProdutoModelTagModel", b =>
                {
                    b.Property<long>("ProdutosId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TagsId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("ProdutosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProdutoModelTagModel");
                });

            modelBuilder.Entity("TagModelUsuarioModel", b =>
                {
                    b.Property<long>("TagsId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TagsId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("TagModelUsuarioModel");
                });

            modelBuilder.Entity("Buyit.Models.AvaliacaoModel", b =>
                {
                    b.HasOne("Buyit.Models.CotacaoModel", "Cotacao")
                        .WithMany()
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotacao");
                });

            modelBuilder.Entity("Buyit.Models.ContatoModel", b =>
                {
                    b.HasOne("Buyit.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buyit.Models.CotacaoModel", b =>
                {
                    b.HasOne("Buyit.Models.UsuarioModel", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.StatusModel", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Produto");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Buyit.Models.HistoricoModel", b =>
                {
                    b.HasOne("Buyit.Models.CotacaoModel", "Cotacao")
                        .WithMany()
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.UsuarioModel", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.StatusModel", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotacao");

                    b.Navigation("Fornecedor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Buyit.Models.ProdutoModel", b =>
                {
                    b.HasOne("Buyit.Models.DepartamentoModel", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("DepartamentoModelTagModel", b =>
                {
                    b.HasOne("Buyit.Models.DepartamentoModel", null)
                        .WithMany()
                        .HasForeignKey("DepartamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProdutoModelTagModel", b =>
                {
                    b.HasOne("Buyit.Models.ProdutoModel", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagModelUsuarioModel", b =>
                {
                    b.HasOne("Buyit.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buyit.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
